# Generated by Django 2.0 on 2018-11-07 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_subscribeuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('category', models.CharField(choices=[('A', 'All Categories'), ('G', 'Granite'), ('M', 'Marble'), ('O', 'Onyx')], default='A', max_length=1)),
                ('description', models.TextField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
