# Generated by Django 2.0 on 2018-11-07 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20181107_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('A', 'All Categories'), ('G', 'Granite'), ('M', 'Marble'), ('O', 'Onyx'), ('H', 'Handicraft')], default='A', max_length=24),
        ),
    ]
