# Generated by Django 2.0 on 2018-11-07 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20181107_0624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('All Categories', 'All Categories'), ('Granite', 'Granite'), ('Marble', 'Marble'), ('Onyx', 'Onyx'), ('Handicraft', 'Handicraft')], default=('All Categories', 'All Categories'), max_length=24),
        ),
    ]
